version: '3'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - server
      - client

  database:
    container_name: database
    build: 
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES-DATABASE=postgres
      - DATABASE_HOST=localhost
      
  server:
    container_name: server
    build: 
      context: ./app/server
      dockerfile: Dockerfile
    ports:
     - 5002:5000
    volumes:
      - ./app/server:/app
    depends_on:
      - database

  client:
    container_name: client
    build:
      context: ./app/client
      dockerfile: Dockerfile
    volumes:
      - './app/client:/app'
      - '/app/node_modules'
    ports:
      - 3008:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVICE_URL=http://localhost:8080
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server